# Part 2.1: Introduction to Pandas and NumPy for Data Analysis

Unfortunately I am unable to include the datasets from Dataquest as they are a subscriber-only feature.

## Introduction to NumPy

Importing the NumPy library and creating a NumPy ndarray:

In [2]:
import numpy as np
data_ndarray = np.array([10, 20, 30])

Importing the nyc_taxis csv and converting to a NumPy array:

In [3]:
from csv import reader
opened_file = open("nyc_taxis.csv", "r", encoding='UTF8')
read_file = reader(opened_file)
taxi_list = list(read_file)

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment

taxi = np.array(converted_taxi_list)

Querying the shape of arrays:

In [4]:
print(taxi)

data_ndarray = np.array([[5, 10, 15],[20, 25, 30]])
print(data_ndarray.shape)

taxi_shape = taxi.shape
print(taxi_shape)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]
(2, 3)
(2013, 15)


Selecting rows/items using NumPy ndarrays:

In [5]:
row_0 = taxi[0]

rows_391_to_500 = taxi[391:501]

row_21_column_5 = taxi[21,5]

Selecting seprated columns/rows/items using NumPy ndarrays.

In [6]:
cols = [1,4,7]
columns_1_4_7 = taxi[:,cols]

row_99_columns_5_to_8 = taxi[99,5:9]

rows_100_to_200_column_14 = taxi[100:201,14]

Vectorized operation:

In [7]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]

fare_and_fees = fare_amount + fees_amount

Vectorized operation:

In [8]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles / trip_length_hours

Calculating statistics for 1D Ndarrays:

In [9]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

Calculating statistics for 2D Ndarrays:

In [10]:
# we'll compare against the first 5 rows only
taxi_first_five = taxi[:5]
# select these columns: fare_amount, fees_amount, tolls_amount, tip_amount
fare_components = taxi_first_five[:,9:13]

fare_sums = fare_components.sum(axis=1)

fare_totals = taxi_first_five[:,13]

print(fare_totals)
print(fare_sums)

[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]


## Boolean Indexing with NumPy

Generating NumPy Ndarrays direct from csv files:

In [16]:
import numpy as np
np.set_printoptions(suppress=True) ## Added this separately as list items were appearing with scientific notation

taxi = np.genfromtxt("nyc_taxis.csv", delimiter=",", dtype=None, encoding=None)
taxi_shape = taxi.shape

print(taxi[:3])
print(taxi.dtype)
print(taxi_shape)

[['pickup_year' 'pickup_month' 'pickup_day' 'pickup_dayofweek'
  'pickup_time' 'pickup_location_code' 'dropoff_location_code'
  'trip_distance' 'trip_length' 'fare_amount' 'fees_amount'
  'tolls_amount' 'tip_amount' 'total_amount' 'payment_type']
 ['2016' '1' '1' '5' '0' '2' '4' '21.00' '2037' '52.00' '0.80' '5.54'
  '11.65' '69.99' '1']
 ['2016' '1' '1' '5' '0' '2' '1' '16.29' '1520' '45.00' '1.30' '0.00'
  '8.00' '54.30' '1']]
<U21
(2014, 15)


genfromtxt, but skipping the header row:

In [17]:
taxi = np.genfromtxt("nyc_taxis.csv", delimiter=",", skip_header=1)

print(taxi[:3])
print(taxi.dtype)
taxi_shape = taxi.shape
print(taxi_shape)

[[2016.      1.      1.      5.      0.      2.      4.     21.   2037.
    52.      0.8     5.54   11.65   69.99    1.  ]
 [2016.      1.      1.      5.      0.      2.      1.     16.29 1520.
    45.      1.3     0.      8.     54.3     1.  ]
 [2016.      1.      1.      5.      0.      2.      6.     12.7  1462.
    36.5     1.3     0.      0.     37.8     2.  ]]
float64
(2013, 15)


Boolean arrays:

In [19]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])

a_bool = a < 3
print(a_bool)
b_bool = b == "blue"
print(b_bool)
c_bool = c > 100
print(c_bool)

[ True  True False False False]
[ True  True False  True]
[False  True False  True]


Using boolean arrays to determine number of rides:

In [21]:
## Create an 1D ndarray that is the first column from the taxis ndarray
pickup_month = taxi[:,1]
print(pickup_month[:4])
print(len(pickup_month))
      
## Create a boolean array of whether the first column in pickup_month is 1
january_bool = pickup_month == 1
print(january_bool[:4])
print(len(january_bool))
      
## Create a new array of pickup_month, filtered using the january_bool index, called january_bool
january = pickup_month[january_bool]
print(january[:4])

## Check the length of the new array, after filtering
january_rides = january.shape[0]
print(january_rides)

## for February
february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]

print(february_rides)

[1. 1. 1. 1.]
2013
[ True  True  True  True]
2013
[1. 1. 1. 1.]
800
176


Boolean Indexing with 2D ndarrays:

In [ ]:
tip_amount = taxi[:,12]

tip_bool = tip_amount > 50

top_tips = taxi[tip_bool,5:14]
print(top_tips)

Modifying values in an array:

In [26]:
taxi_modified = taxi.copy()
taxi_modified[1066:5] = 1
taxi_modified[:,0] = 16
taxi_modified[550:552,7] = taxi_modified[:,7].mean()

print(taxi_modified.shape)
print(taxi_modified[548:554,5:9])

(2013, 15)
[[   2.            1.           12.18       2300.        ]
 [   2.            6.           15.8        1824.        ]
 [   3.            4.           12.92477894 1074.        ]
 [   3.            4.           12.92477894  974.        ]
 [   2.            4.           20.02       1979.        ]
 [   3.            6.            3.8         572.        ]]


Assigning values using boolean arrays:

In [27]:
taxi_copy = taxi.copy()

## create a 1D array of values in the 14th column (index 13) of the taxi_copy array
total_amount = taxi_copy[:,13]

## modifying values in this array based on TRUE responses to a criteria
total_amount[total_amount < 0] = 0

In [28]:
## bool = array[:, column_for_comparison] == value_for_comparison
## array[bool, column_for_assignment] = new_value

## create a new array based on the length of another
## name of array (zeros) = an array full of zeroes (np.zeros), with number of rows equal to the number of rows in taxi (taxi.shape[0]), and 1 column ([1])
zeros = np.zeros([taxi.shape[0],1])

## new array = combination (np.concatenate) of the 'taxi' array, and the 'zeros' array, along the column axis(1)
taxi_modified = np.concatenate([taxi,zeros],axis=1)
print(taxi_modified)

## longer method of assigning values:

## jfk_bool is a boolean array of all rows based on if the values in the 6th column are equal to 2
jfk_bool = taxi_modified[:, 5] == 2

## modifying values in the taxi_modified 16th column to 0 based on the boolean
## in the 'taxi_modified' array, 'rows equal to those with the True value' and 'column 16' = 1
taxi_modified[jfk_bool,15] = 1

## shorter methods:

## in the 'taxi_modified' array, the rows chosen are:
    ## a boolean array based on the 'taxi_modified' array where the value in the 6th column is 2 // taxi_modified[:, 5] == 2
## the column chosen is the one at index 15 (16th column)
## the new value is 1
taxi_modified[taxi_modified[:, 5] == 2, 15] = 1

taxi_modified[taxi_modified[:, 5] == 3, 15] = 1
taxi_modified[taxi_modified[:, 5] == 5, 15] = 1
print('\n')
print(taxi_modified)

[[2016.      1.      1.   ...   69.99    1.      0.  ]
 [2016.      1.      1.   ...   54.3     1.      0.  ]
 [2016.      1.      1.   ...   37.8     2.      0.  ]
 ...
 [2016.      6.     30.   ...   63.34    1.      0.  ]
 [2016.      6.     30.   ...   44.75    1.      0.  ]
 [2016.      6.     30.   ...   54.84    2.      0.  ]]


[[2016.      1.      1.   ...   69.99    1.      1.  ]
 [2016.      1.      1.   ...   54.3     1.      1.  ]
 [2016.      1.      1.   ...   37.8     2.      1.  ]
 ...
 [2016.      6.     30.   ...   63.34    1.      1.  ]
 [2016.      6.     30.   ...   44.75    1.      1.  ]
 [2016.      6.     30.   ...   54.84    2.      1.  ]]


Determining which airport had the highest number of flights inbound:

In [33]:
## jfk is an array based on the taxi array, with all the columns, but where the 7th column in the taxi array is 2
jfk = taxi[taxi[:,6] == 2]

## jfk_count is a value equal to the shape of the jfk array, on the 0(row) axis
jfk_count = jfk.shape[0]
print(type(jfk_count))
print(jfk_count)

laguardia = taxi[taxi[:,6] == 3]
laguardia_count = laguardia.shape[0]
print(laguardia_count)

newark = taxi[taxi[:,6] == 5]
newark_count = newark.shape[0]
print(newark_count)

<class 'int'>
285
308
2


Calculating Statistics for Trips on Clean Data

In [35]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)

##cleaned_taxi is an array based on the taxi array, where the rows chosen are a boolean array based on whether trip_mph < 100,
cleaned_taxi = taxi[trip_mph<100]

## the mean_distance int is the mean of the values in the 8th column of the cleaned_taxi array
mean_distance = cleaned_taxi[:,7].mean()
print(round(mean_distance,2),"miles on average")

mean_length = cleaned_taxi[:,8].mean() / 60
print(round(mean_length,2),"minutes on average")

mean_total_amount = cleaned_taxi[:,13].mean()
print(round(mean_total_amount,2),"dollars on average")

12.9 miles on average
37.86 minutes on average
48.7 dollars on average


## Introduction to pandas

Importing pandas, reading csvs into dataframes, determining the type and shape of dataframes:

In [67]:
import pandas as pd
f500 = pd.read_csv('f500.csv',index_col=0)
f500.index.name = None

print("First two rows are:")
print(f500[:1])
print('\n')

f500_type = type(f500)
print("Class is")
print(f500_type)
print('\n')

f500_shape = f500.shape
print("Shape is")
print(f500_shape)

First two rows are:
         rank  revenues  revenue_change  profits  assets  profit_change  \
Walmart     1    485873             0.8  13643.0  198825           -7.2   

                         ceo               industry     sector  previous_rank  \
Walmart  C. Douglas McMillon  General Merchandisers  Retailing              1   

        country      hq_location                 website  \
Walmart     USA  Bentonville, AR  http://www.walmart.com   

         years_on_global_500_list  employees  total_stockholder_equity  
Walmart                        23    2300000                     77798  


Class is
<class 'pandas.core.frame.DataFrame'>


Shape is
(500, 16)


Printing head and tail of a dataframe:

In [ ]:
f500_head = f500.head(6)
print(f500_head)

f500_tail = f500.tail(8)
print(f500_tail)

Inspecting the information and data types in the dataframe:

In [69]:
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      500 non-null    int64  
 1   revenues                  500 non-null    int64  
 2   revenue_change            498 non-null    float64
 3   profits                   499 non-null    float64
 4   assets                    500 non-null    int64  
 5   profit_change             436 non-null    float64
 6   ceo                       500 non-null    object 
 7   industry                  500 non-null    object 
 8   sector                    500 non-null    object 
 9   previous_rank             500 non-null    int64  
 10  country                   500 non-null    object 
 11  hq_location               500 non-null    object 
 12  website                   500 non-null    object 
 13  years_on_global_500_list  500 non-null    int64  
 14  em

Creating a series by selecting a specific column by name from a dataframe:

In [72]:
industries=f500["industry"]
industries_type=type(industries)
print(industries)
print('\n')
print(industries_type)

Walmart                                     General Merchandisers
State Grid                                              Utilities
Sinopec Group                                  Petroleum Refining
China National Petroleum                       Petroleum Refining
Toyota Motor                             Motor Vehicles and Parts
                                               ...               
Teva Pharmaceutical Industries                    Pharmaceuticals
New China Life Insurance          Insurance: Life, Health (stock)
Wm. Morrison Supermarkets                    Food and Drug Stores
TUI                                               Travel Services
AutoNation                                    Specialty Retailers
Name: industry, Length: 500, dtype: object


<class 'pandas.core.series.Series'>


Selecting columns from a dataframe by label:

In [79]:
## A single series only needs [""]
countries = f500["country"]

## Multiple columns requires [["",""]]
revenues_years = f500[["revenues","years_on_global_500_list"]]

## A slice of columns requires .loc[:,"":""]
ceo_to_sector = f500.loc[:,"ceo":"sector"]

print(type(countries))
print(type(revenues_years))
print(type(ceo_to_sector))
print(countries.head())
print(revenues_years.head())
print(ceo_to_sector.head())

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
Walmart                       USA
State Grid                  China
Sinopec Group               China
China National Petroleum    China
Toyota Motor                Japan
Name: country, dtype: object
                          revenues  years_on_global_500_list
Walmart                     485873                        23
State Grid                  315199                        17
Sinopec Group               267518                        19
China National Petroleum    262573                        17
Toyota Motor                254694                        23
                                          ceo                  industry  \
Walmart                   C. Douglas McMillon     General Merchandisers   
State Grid                            Kou Wei                 Utilities   
Sinopec Group                       Wang Yupu        Petroleum Refining   
China National Petroleu

Selecting rows from a dataFrame by label:

In [80]:
## Syntax to select rows and columns from a dataframe:
## df.loc[row_label, column_label]

## selecting a single row
toyota = f500.loc["Toyota Motor"]
print(type(toyota))
print(toyota)

## select a list of rows
drink_companies = f500.loc[["Anheuser-Busch InBev", "Coca-Cola", "Heineken Holding"]]
print(type(drink_companies))
print(drink_companies)

## select a slice object with labels
middle_companies = f500.loc["Tata Motors":"Nationwide","rank":"country"]
print(type(middle_companies))
print(middle_companies)

<class 'pandas.core.series.Series'>
rank                                                   5
revenues                                          254694
revenue_change                                       7.7
profits                                          16899.3
assets                                            437575
profit_change                                      -12.3
ceo                                          Akio Toyoda
industry                        Motor Vehicles and Parts
sector                            Motor Vehicles & Parts
previous_rank                                          8
country                                            Japan
hq_location                                Toyota, Japan
website                     http://www.toyota-global.com
years_on_global_500_list                              23
employees                                         364445
total_stockholder_equity                          157210
Name: Toyota Motor, dtype: object
<class 'pandas.cor

Using value counts:

In [81]:
countries = f500["country"]
country_counts = countries.value_counts()
print(country_counts)
print(type(country_counts))

USA             132
China           109
Japan            51
Germany          29
France           29
Britain          24
South Korea      15
Netherlands      14
Switzerland      14
Canada           11
Spain             9
Australia         7
Brazil            7
India             7
Italy             7
Taiwan            6
Russia            4
Ireland           4
Singapore         3
Sweden            3
Mexico            2
Malaysia          1
Thailand          1
Belgium           1
Norway            1
Luxembourg        1
Indonesia         1
Denmark           1
Saudi Arabia      1
Finland           1
Venezuela         1
Turkey            1
U.A.E             1
Israel            1
Name: country, dtype: int64
<class 'pandas.core.series.Series'>


Selecting items from a series by label:

In [82]:
countries = f500['country']
countries_counts = countries.value_counts()

india = countries_counts["India"]
north_america = countries_counts[["USA","Canada","Mexico"]]

print(india)
print('\n')
print(north_america)

7


USA       132
Canada     11
Mexico      2
Name: country, dtype: int64


Practising:

In [83]:
big_movers = f500.loc[["Aviva","HP","JD.com","BHP Billiton"],["rank","previous_rank"]]
print(big_movers.head())
bottom_companies = f500.loc["National Grid":"AutoNation",["rank","sector","country"]]
print(bottom_companies.head())

              rank  previous_rank
Aviva           90            279
HP             194             48
JD.com         261            366
BHP Billiton   350            168
                                       rank              sector  country
National Grid                           491              Energy  Britain
Dollar General                          492           Retailing      USA
Telecom Italia                          493  Telecommunications    Italy
Xiamen ITG Holding Group                494         Wholesalers    China
Xinjiang Guanghui Industry Investment   495         Wholesalers    China


## Exploring Data with Pandas: Fundamentals

## Exploring Data with Pandas: Intermediate

## Data Cleaning Basics

## Guided Project: Exploring eBay Car Sales Data